import { useState } from'react';
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from'@/components/ui/card';
import { Button } from'@/components/ui/button';
import { Badge } from'@/components/ui/badge';
import { Tabs,TabsContent,TabsList,TabsTrigger } from'@/components/ui/tabs';
import { useAuth } from'@/contexts/AuthContext';
import { 
FileText,
X,
Car,
User,
Wrench,
Calendar,
Eye,
Download,
Clock,
CheckCircle,
AlertCircle,
XCircle,
Package,
Users
 } from'lucide-react';

interfaceClaimDetailsProps{
claimId:string;
onClose:()=>void;
onUpdateStatus:()=>void;
}

const ClaimDetails=({claimId,onClose,onUpdateStatus}:ClaimDetailsProps)=>{
const{user}=useAuth();

//Mockclaimdata-inrealappwouldfetchbyclaimId
const claimData={
id:claimId,
vin:'1HGBH41JXMN109186',
customer:{
name:'NguyễnVănMinh',
phone:'0901234567',
email:'minh.nguyen@email.com',
address:'123ĐườngABC,Quận1,TP.HCM'
},
vehicle:{
model:'EVModelXPro',
year:'2023',
color:'TrắngNgọcTrai',
batteryCapacity:'75kWh',
motorType:'DualMotorAWD',
purchaseDate:'2023-03-15',
warrantyStatus:'Active-7.2yearsremaining'
},
issue:{
category:'BatteryPerformanceIssue',
description:'Kháchhàngbáocáopinsạcchậmvàgiảmdunglượngđángkể.Thờigiansạctừ20%lên80%mất45phútthayvì25phútnhưbanđầu.Rangethựctếchỉđạt320kmthayvì450kmnhưcôngbố.',
reportedDate:'2024-01-15',
priority:'high'
},
technicians:[
{id:'tech-1',name:'TrầnMinhQuân',role:'LeadTechnician',specialty:'BatterySystems'},
{id:'tech-2',name:'LêThịHoa',role:'SupportTechnician',specialty:'Diagnostics'}
],
diagnosis:{
summary:'Saukiểmtrachitiết,pháthiện3cellpintrongmoduleB2códấuhiệusuygiảmnghiêmtrọng.BMSbáolỗimãP0A80-Highvoltagebatterypackdegradation.Cầnthaythếtoànbộbatterypack.',
errorCodes:['P0A80','P0A7F','P3009'],
testResults:[
{test:'BatteryCapacityTest',result:'68.2kWh',expected:'75kWh',status:'fail'},
{test:'CellVoltageBalance',result:'Unbalanced',expected:'Balanced',status:'fail'},
{test:'ChargingCurrent',result:'45A',expected:'125A',status:'fail'},
{test:'BatteryTemperature',result:'32°C',expected:'<30°C',status:'pass'}
],
recommendation:'Thaythếbatterypacktheoquytrìnhwarranty.Estimatedcost:15,000,000VND.'
},
attachments:[
{name:'Battery_Diagnostic_Report.pdf',size:'2.4MB',type:'pdf',uploadDate:'2024-01-15'},
{name:'Error_Code_Screenshot.jpg',size:'856KB',type:'image',uploadDate:'2024-01-15'},
{name:'Cell_Voltage_Chart.xlsx',size:'1.2MB',type:'excel',uploadDate:'2024-01-16'},
{name:'Battery_Photos_1.jpg',size:'3.1MB',type:'image',uploadDate:'2024-01-16'}
],
status:'pending',
timeline:[
{date:'2024-01-1509:30',event:'ClaimCreated',user:'NguyễnVănA(Staff)',status:'created'},
{date:'2024-01-1510:15',event:'TechnicianAssigned',user:'System',status:'assigned'},
{date:'2024-01-1514:30',event:'DiagnosticStarted',user:'TrầnMinhQuân',status:'diagnosing'},
{date:'2024-01-1611:20',event:'DiagnosticComplete',user:'TrầnMinhQuân',status:'diagnosed'},
{date:'2024-01-1616:45',event:'SubmittedtoManufacturer',user:'NguyễnVănA(Staff)',status:'pending'}
],
estimatedCost:'15,000,000VND',
createdBy:'NguyễnVănA',
createdDate:'2024-01-15'
};

const getStatusBadge=(status))=>{
const statusConfig={
pending:{variant:"pending",icon:Clock,text:"Chờduyệt"},
approved:{variant:"approved",icon:CheckCircle,text:"Đãduyệt"},
rejected:{variant:"rejected",icon:XCircle,text:"Từchối"},
"in-progress":{variant:"warning",icon:Wrench,text:"Đangsửa"},
completed:{variant:"success",icon:CheckCircle,text:"Hoànthành"}
};

const config=statusConfig[statusaskeyoftypeofstatusConfig];
if(!config)returnnull;

const Icon=config.icon;
return(
<Badgevariant={config.variant}>
<IconclassName="mr-1h-3w-3"/>
{config.text}
</Badge>
);
};

const getPriorityBadge=(priority))=>{
const priorityConfig={
high:{variant:"destructive",text:"Cao"},
medium:{variant:"warning",text:"Trungbình"},
low:{variant:"secondary",text:"Thấp"}
};

const config=priorityConfig[priorityaskeyoftypeofpriorityConfig];
return<Badgevariant={config.variant}>{config.text}</Badge>;
};

const getTestStatusBadge=(status))=>{
returnstatus==='pass'
<Badgevariant="success">Pass</Badge>:
<Badgevariant="destructive">Fail</Badge>;
};

return(
<divclassName="fixedinset-0bg-black/50flexitems-centerjustify-centerp-4z-50">
<CardclassName="w-fullmax-w-6xlmax-h-[90vh]overflow-hidden">
<CardHeaderclassName="border-b">
<divclassName="flexitems-centerjustify-between">
<div>
<CardTitleclassName="flexitems-centerspace-x-2">
<FileTextclassName="h-5w-5text-primary"/>
<span>WarrantyClaimDetails</span>
</CardTitle>
<CardDescription>
ClaimID:{claimData.id}|Created:{claimData.createdDate}
</CardDescription>
</div>
<divclassName="flexitems-centerspace-x-2">
{getStatusBadge(claimData.status)}
<Buttonvariant="ghost"size="sm"onClick={onClose}>
<XclassName="h-4w-4"/>
</Button>
</div>
</div>
</CardHeader>

<CardContentclassName="p-0">
<TabsdefaultValue="overview"className="h-full">
<divclassName="border-bpx-6">
<TabsListclassName="gridw-fullgrid-cols-5">
<TabsTriggervalue="overview">Overview</TabsTrigger>
<TabsTriggervalue="diagnosis">Diagnosis</TabsTrigger>
<TabsTriggervalue="attachments">Files</TabsTrigger>
<TabsTriggervalue="timeline">Timeline</TabsTrigger>
<TabsTriggervalue="actions">Actions</TabsTrigger>
</TabsList>
</div>

<divclassName="p-6overflow-y-automax-h-[calc(90vh-280px)]">
{/*OverviewTab*/}
<TabsContentvalue="overview"className="space-y-6">
<divclassName="gridlg:grid-cols-2gap-6">
{/*Customer&VehicleInfo*/}
<Card>
<CardHeader>
<CardTitleclassName="flexitems-centerspace-x-2text-base">
<UserclassName="h-4w-4"/>
<span>CustomerInformation</span>
</CardTitle>
</CardHeader>
<CardContentclassName="space-y-3">
<div>
<pclassName="text-smtext-muted-foreground">Name</p>
<pclassName="font-medium">{claimData.customer.name}</p>
</div>
<div>
<pclassName="text-smtext-muted-foreground">Contact</p>
<pclassName="font-medium">{claimData.customer.phone}</p>
<pclassName="text-smtext-muted-foreground">{claimData.customer.email}</p>
</div>
<div>
<pclassName="text-smtext-muted-foreground">Address</p>
<pclassName="font-medium">{claimData.customer.address}</p>
</div>
</CardContent>
</Card>

<Card>
<CardHeader>
<CardTitleclassName="flexitems-centerspace-x-2text-base">
<CarclassName="h-4w-4"/>
<span>VehicleInformation</span>
</CardTitle>
</CardHeader>
<CardContentclassName="space-y-3">
<div>
<pclassName="text-smtext-muted-foreground">Model&Year</p>
<pclassName="font-medium">{claimData.vehicle.model}({claimData.vehicle.year})</p>
</div>
<div>
<pclassName="text-smtext-muted-foreground">VIN</p>
<pclassName="font-mediumfont-mono">{claimData.vin}</p>
</div>
<divclassName="gridgrid-cols-2gap-4">
<div>
<pclassName="text-smtext-muted-foreground">Color</p>
<pclassName="font-medium">{claimData.vehicle.color}</p>
</div>
<div>
<pclassName="text-smtext-muted-foreground">Battery</p>
<pclassName="font-medium">{claimData.vehicle.batteryCapacity}</p>
</div>
</div>
<div>
<pclassName="text-smtext-muted-foreground">WarrantyStatus</p>
<Badgevariant="success">{claimData.vehicle.warrantyStatus}</Badge>
</div>
</CardContent>
</Card>

{/*IssueDetails*/}
<CardclassName="lg:col-span-2">
<CardHeader>
<CardTitleclassName="flexitems-centerjustify-betweentext-base">
<divclassName="flexitems-centerspace-x-2">
<AlertCircleclassName="h-4w-4"/>
<span>IssueDetails</span>
</div>
<divclassName="flexitems-centerspace-x-2">
{getPriorityBadge(claimData.issue.priority)}
<Badgevariant="outline">{claimData.issue.category}</Badge>
</div>
</CardTitle>
</CardHeader>
<CardContent>
<divclassName="space-y-4">
<div>
<pclassName="text-smtext-muted-foreground">ReportedDate</p>
<pclassName="font-medium">{newDate(claimData.issue.reportedDate).toLocaleDateString('vi-VN')}</p>
</div>
<div>
<pclassName="text-smtext-muted-foreground">Description</p>
<pclassName="text-smleading-relaxed">{claimData.issue.description}</p>
</div>
<div>
<pclassName="text-smtext-muted-foreground">EstimatedCost</p>
<pclassName="font-semiboldtext-lgtext-primary">{claimData.estimatedCost}</p>
</div>
</div>
</CardContent>
</Card>

{/*AssignedTechnicians*/}
<CardclassName="lg:col-span-2">
<CardHeader>
<CardTitleclassName="flexitems-centerspace-x-2text-base">
<UsersclassName="h-4w-4"/>
<span>AssignedTechnicians</span>
</CardTitle>
</CardHeader>
<CardContent>
<divclassName="gridmd:grid-cols-2gap-4">
{claimData.technicians.map((tech)=>(
<divkey={tech.id}className="flexitems-centerspace-x-3p-3borderrounded-lg">
<divclassName="h-10w-10rounded-fullbg-accentflexitems-centerjustify-center">
<WrenchclassName="h-5w-5"/>
</div>
<div>
<pclassName="font-medium">{tech.name}</p>
<pclassName="text-smtext-muted-foreground">{tech.role}</p>
<pclassName="text-xstext-muted-foreground">{tech.specialty}</p>
</div>
</div>
))}
</div>
</CardContent>
</Card>
</div>
</TabsContent>

{/*DiagnosisTab*/}
<TabsContentvalue="diagnosis"className="space-y-6">
<Card>
<CardHeader>
<CardTitleclassName="text-base">TechnicalDiagnosisSummary</CardTitle>
</CardHeader>
<CardContent>
<pclassName="text-smleading-relaxed">{claimData.diagnosis.summary}</p>
</CardContent>
</Card>

<Card>
<CardHeader>
<CardTitleclassName="text-base">ErrorCodes</CardTitle>
</CardHeader>
<CardContent>
<divclassName="flexflex-wrapgap-2">
{claimData.diagnosis.errorCodes.map((code)=>(
<Badgekey={code}variant="destructive"className="font-mono">{code}</Badge>
))}
</div>
</CardContent>
</Card>

<Card>
<CardHeader>
<CardTitleclassName="text-base">TestResults</CardTitle>
</CardHeader>
<CardContent>
<divclassName="space-y-3">
{claimData.diagnosis.testResults.map((test,index)=>(
<divkey={index}className="flexitems-centerjustify-betweenp-3borderrounded-lg">
<div>
<pclassName="font-medium">{test.test}</p>
<pclassName="text-smtext-muted-foreground">
Result:<spanclassName="font-mono">{test.result}</span>|
Expected:<spanclassName="font-mono">{test.expected}</span>
</p>
</div>
{getTestStatusBadge(test.status)}
</div>
))}
</div>
</CardContent>
</Card>

<Card>
<CardHeader>
<CardTitleclassName="text-base">Recommendation</CardTitle>
</CardHeader>
<CardContent>
<pclassName="text-smleading-relaxed">{claimData.diagnosis.recommendation}</p>
</CardContent>
</Card>
</TabsContent>

{/*AttachmentsTab*/}
<TabsContentvalue="attachments"className="space-y-4">
<Card>
<CardHeader>
<CardTitleclassName="text-base">SupportingDocuments({claimData.attachments.length})</CardTitle>
</CardHeader>
<CardContent>
<divclassName="space-y-3">
{claimData.attachments.map((file,index)=>(
<divkey={index}className="flexitems-centerjustify-betweenp-3borderrounded-lg">
<divclassName="flexitems-centerspace-x-3">
<divclassName="h-8w-8roundedbg-accentflexitems-centerjustify-center">
<FileTextclassName="h-4w-4"/>
</div>
<div>
<pclassName="font-medium">{file.name}</p>
<pclassName="text-smtext-muted-foreground">
{file.size}|Uploaded:{newDate(file.uploadDate).toLocaleDateString('vi-VN')}
</p>
</div>
</div>
<divclassName="flexspace-x-2">
<Buttonvariant="ghost"size="sm">
<EyeclassName="h-4w-4"/>
</Button>
<Buttonvariant="ghost"size="sm">
<DownloadclassName="h-4w-4"/>
</Button>
</div>
</div>
))}
</div>
</CardContent>
</Card>
</TabsContent>

{/*TimelineTab*/}
<TabsContentvalue="timeline"className="space-y-4">
<Card>
<CardHeader>
<CardTitleclassName="text-base">ClaimTimeline</CardTitle>
</CardHeader>
<CardContent>
<divclassName="space-y-4">
{claimData.timeline.map((event,index)=>(
<divkey={index}className="flexitems-startspace-x-3">
<divclassName="flexh-8w-8items-centerjustify-centerrounded-fullbg-primarytext-primary-foregroundtext-xs">
{index+1}
</div>
<divclassName="flex-1">
<divclassName="flexitems-centerjustify-between">
<pclassName="font-medium">{event.event}</p>
<pclassName="text-smtext-muted-foreground">{event.date}</p>
</div>
<pclassName="text-smtext-muted-foreground">by{event.user}</p>
</div>
</div>
))}
</div>
</CardContent>
</Card>
</TabsContent>

{/*ActionsTab*/}
<TabsContentvalue="actions"className="space-y-4">
<Card>
<CardHeader>
<CardTitleclassName="text-base">AvailableActions</CardTitle>
<CardDescription>
Actionsavailableforthisclaimbasedoncurrentstatusandyourrole
</CardDescription>
</CardHeader>
<CardContent>
<divclassName="gridmd:grid-cols-2gap-4">
<Button
className="w-full"
onClick={onUpdateStatus}
disabled={user.role!=='service_center_staff'}
>
UpdateStatus
</Button>
<Buttonvariant="outline"className="w-full">
AddNotes
</Button>
<Buttonvariant="outline"className="w-full">
UploadFiles
</Button>
<Buttonvariant="outline"className="w-full">
PrintReport
</Button>
</div>

{user.role!=='service_center_staff'&&(
<pclassName="text-smtext-muted-foregroundmt-4">
*SomeactionsarerestrictedtoStaffmembers
</p>
)}
</CardContent>
</Card>
</TabsContent>
</div>
</Tabs>
</CardContent>
</Card>
</div>
);
};

exportdefaultClaimDetails;